name: eShopOnWeb Build and Deploy

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: Indra22
  LOCATION: eastus2
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 239a12fd-fdfd-4e9d-8cec-45c05d6c6c9a
  WEBAPP-NAME: eshoponweb-webapp-indra22

jobs:
  #Build and publish .net web project in repository
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release

    - name: dotnet publish
      run: |
        dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        cd ${{env.DOTNET_ROOT}}/myapp
        zip -r ../app.zip .

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/app.zip

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: .net-app

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: bicep-template
        path: bicep-template

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION-ID }}
        resourceGroupName: ${{ env.RESOURCE-GROUP }}
        template: bicep-template/webapp.bicep
        parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
        failOnStdErr: false   

    - name: Publish Website to WebApp
      uses: Azure/cli@v2
      with:
        inlineScript: |
             az webapp deploy --name ${{ env.WEBAPP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --src-path .net-app/app.zip --type zip
